apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-custom-react-template-${{values.component_id | lower}}
  description: Custom React Template - ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}

